apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: akkeris-ui
  name: akkeris-ui
  namespace: akkeris-system
spec:
  replicas: 2
  selector:
    matchLabels:
      name: akkeris-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: akkeris-ui
      name: akkeris-ui
    spec:
      containers:
        image: akkeris/apache_test:latest
        imagePullPolicy: Always
        name: akkeris-ui
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60