apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: apache-test
  name: apache-test
  namespace: akkeris-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: apache-test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: apache-test
      name: apache-test
    spec:
      containers:
      - image: akkeris/apachetest
        imagePullPolicy: Always
        name: apache-test
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      
    
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: apache-test
  name: apache-test
  namespace: akkeris-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: tcp
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: apache-test
  sessionAffinity: None
  type: NodePort

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apache-test
  namespace: sites-system
spec:
  gateways:
  - sites-public
  hosts:
  - apache-test.octanner.io
  http:
  - route:
    - destination:
        host: apache-test.akkeris-system.svc.cluster.local
        port:
          number: 80
